<form method="POST" action="{{ $formAction }}" enctype="multipart/form-data" class="max-w-3xl rounded-2xl border border-earth/10 bg-[#fffdfa] p-6 shadow-sm sm:p-8">
    @csrf
    @if ($formMethod !== 'POST') @method($formMethod) @endif
    @if ($errors->any())
        <div class="mb-6 rounded-xl border border-[#b05f50]/20 bg-[#b05f50]/10 px-4 py-3 text-sm text-[#8e4135]"><p class="font-bold">Please check the form.</p><ul class="mt-1 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
    @endif
    <div class="grid gap-6 sm:grid-cols-2">
        <label class="block"><span class="text-sm font-bold text-earth">Image title <span class="font-normal text-earth-light">(optional for multiple uploads)</span></span><input name="title" value="{{ old('title', $galleryImage->title) }}" {{ $formMethod === 'POST' ? '' : 'required' }} class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">Leave blank during bulk upload to use each filename.</span></label>
        <label class="block"><span class="text-sm font-bold text-earth">Category</span><select name="category" required class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf">@foreach(['Crops', 'Livestock', 'Training', 'Equipment', 'Facilities'] as $category)<option value="{{ $category }}" @selected(old('category', $galleryImage->category ?: 'Crops') === $category)>{{ $category }}</option>@endforeach</select></label>
        <label class="block sm:col-span-2"><span class="text-sm font-bold text-earth">{{ $formMethod === 'POST' ? 'Upload images' : 'Replace image' }}</span><input type="file" name="{{ $formMethod === 'POST' ? 'images[]' : 'image' }}" accept="image/jpeg,image/png,image/webp" {{ $formMethod === 'POST' ? 'multiple required' : '' }} class="mt-2 block w-full rounded-xl border border-earth/20 bg-white px-4 py-3 text-sm file:mr-4 file:border-0 file:bg-cream file:px-4 file:py-2.5 file:font-bold file:text-earth focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">JPG, PNG, or WebP up to 5 MB each. You can select up to 30 images at once.</span>@if ($galleryImage->image_url)<img src="{{ $galleryImage->image_url }}" alt="Current {{ $galleryImage->title }} image" class="mt-4 h-28 w-40 rounded-xl object-cover">@endif</label>
        <label class="block"><span class="text-sm font-bold text-earth">Display order</span><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $galleryImage->sort_order ?: 1) }}" required class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">Lower numbers appear first.</span></label>
    </div>
    <label class="mt-6 block"><span class="text-sm font-bold text-earth">Description <span class="font-normal text-earth-light">(optional)</span></span><textarea name="description" rows="4" class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf">{{ old('description', $galleryImage->description) }}</textarea></label>
    <div class="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('gallery-images.index') }}" class="inline-flex items-center justify-center rounded-xl border border-earth/15 px-5 py-3 text-sm font-bold text-earth hover:bg-cream">Cancel</a><button type="submit" class="inline-flex items-center justify-center rounded-xl bg-earth px-5 py-3 text-sm font-bold text-white hover:bg-earth-dark">{{ $formMethod === 'POST' ? 'Add image' : 'Save changes' }}</button></div>
</form>