<form method="POST" action="{{ $formAction }}" enctype="multipart/form-data" class="max-w-3xl rounded-2xl border border-earth/10 bg-[#fffdfa] p-6 shadow-sm sm:p-8">
    @csrf
    @if ($formMethod !== 'POST') @method($formMethod) @endif
    @if ($errors->any())
        <div class="mb-6 rounded-xl border border-[#b05f50]/20 bg-[#b05f50]/10 px-4 py-3 text-sm text-[#8e4135]"><p class="font-bold">Please check the form.</p><ul class="mt-1 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
    @endif
    <div class="grid gap-6 sm:grid-cols-2">
        <label class="block"><span class="text-sm font-bold text-earth">Full name</span><input name="name" value="{{ old('name', $teamMember->name) }}" required class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">The name shown publicly.</span></label>
        <label class="block"><span class="text-sm font-bold text-earth">Role</span><input name="role" value="{{ old('role', $teamMember->role) }}" required class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"></label>
        <label class="block"><span class="text-sm font-bold text-earth">Title <span class="font-normal text-earth-light">(optional)</span></span><input name="title" value="{{ old('title', $teamMember->title) }}" class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"></label>
        <label class="block"><span class="text-sm font-bold text-earth">Display order</span><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $teamMember->sort_order ?: 1) }}" required class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">Lower numbers appear first.</span></label>
    </div>
    <label class="mt-6 block"><span class="text-sm font-bold text-earth">Photo <span class="font-normal text-earth-light">(optional)</span></span><input type="file" name="image" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full rounded-xl border border-earth/20 bg-white px-4 py-3 text-sm file:mr-4 file:border-0 file:bg-cream file:px-4 file:py-2.5 file:font-bold file:text-earth focus:border-leaf focus:ring-leaf"><span class="mt-1 block text-xs text-earth-light">JPG, PNG, or WebP up to 5 MB.</span>@if ($teamMember->image)<img src="{{ asset($teamMember->image) }}" alt="Current {{ $teamMember->name }} photo" class="mt-4 h-28 w-28 rounded-xl object-cover">@endif</label>
    <label class="mt-6 block"><span class="text-sm font-bold text-earth">Bio <span class="font-normal text-earth-light">(optional)</span></span><textarea name="bio" rows="5" class="mt-2 w-full rounded-xl border-earth/20 bg-white px-4 py-3 text-sm focus:border-leaf focus:ring-leaf">{{ old('bio', $teamMember->bio) }}</textarea></label>
    <div class="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('team-members.index') }}" class="inline-flex items-center justify-center rounded-xl border border-earth/15 px-5 py-3 text-sm font-bold text-earth hover:bg-cream">Cancel</a><button type="submit" class="inline-flex items-center justify-center rounded-xl bg-earth px-5 py-3 text-sm font-bold text-white hover:bg-earth-dark">{{ $formMethod === 'POST' ? 'Add member' : 'Save changes' }}</button></div>
</form>